CREATE DATABASE COMERCIO_DB;
GO
USE COMERCIO_DB;
GO

IF OBJECT_ID('dbo.DETALLE_VENTA', 'U') IS NOT NULL
    DROP TABLE dbo.DETALLE_VENTA;
GO
IF OBJECT_ID('dbo.VENTAS', 'U') IS NOT NULL
    DROP TABLE dbo.VENTAS;
GO
IF OBJECT_ID('dbo.PRECIOS_COMPRA', 'U') IS NOT NULL
    DROP TABLE dbo.PRECIOS_COMPRA;
GO
IF OBJECT_ID('dbo.CLIENTES', 'U') IS NOT NULL
    DROP TABLE dbo.CLIENTES;
GO
IF OBJECT_ID('dbo.USUARIO_ROLES', 'U') IS NOT NULL
    DROP TABLE dbo.USUARIO_ROLES;
GO
IF OBJECT_ID('dbo.ROLES', 'U') IS NOT NULL
    DROP TABLE dbo.ROLES;
GO
IF OBJECT_ID('dbo.USUARIOS', 'U') IS NOT NULL
    DROP TABLE dbo.USUARIOS;
GO
IF OBJECT_ID('dbo.PRODUCTOS', 'U') IS NOT NULL
    DROP TABLE dbo.PRODUCTOS;
GO
IF OBJECT_ID('dbo.ARTICULOS', 'U') IS NOT NULL
    DROP TABLE dbo.ARTICULOS;
GO
IF OBJECT_ID('dbo.PROVEEDORES', 'U') IS NOT NULL
    DROP TABLE dbo.PROVEEDORES;
GO
IF OBJECT_ID('dbo.CATEGORIAS', 'U') IS NOT NULL
    DROP TABLE dbo.CATEGORIAS;
GO
IF OBJECT_ID('dbo.MARCAS', 'U') IS NOT NULL
    DROP TABLE dbo.MARCAS;
GO

CREATE TABLE CATEGORIAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);
GO

CREATE TABLE MARCAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);
GO

CREATE TABLE PROVEEDORES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NULL,
    RazonSocial VARCHAR(200) NOT NULL,
    Documento VARCHAR(20) NULL UNIQUE,
    Email VARCHAR(100) NULL,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    CondicionIVA VARCHAR(50) NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE PRODUCTOS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CodigoSKU VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    IdMarca INT NULL,
    IdCategoria INT NOT NULL,
    IdProveedor INT NULL,
    StockMinimo DECIMAL(18, 2) NULL,
    StockActual DECIMAL(18, 2) NULL,
    PorcentajeGanancia DECIMAL(5, 2) NULL,
    UrlImagen VARCHAR(1000) NULL,
    Activo BIT NOT NULL DEFAULT(1),
    CONSTRAINT FK_PRODUCTOS_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCAS(Id),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIAS(Id),
    CONSTRAINT FK_PRODUCTOS_PROVEEDOR FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id)
);
GO

CREATE TABLE PRECIOS_COMPRA (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdProducto INT NOT NULL,
    IdProveedor INT NULL,
    Precio MONEY NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT FK_PRECIOS_COMPRA_PRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id),
    CONSTRAINT FK_PRECIOS_COMPRA_PROVEEDOR FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id)
);
GO

CREATE TABLE USUARIOS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(50) NULL,
    Documento VARCHAR(20) NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Activo BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE ROLES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);
GO

INSERT INTO ROLES (Descripcion) VALUES ('Admin'), ('Vendedor');
GO

CREATE TABLE USUARIO_ROLES (
    IdUsuario INT NOT NULL,
    IdRol INT NOT NULL,
    PRIMARY KEY (IdUsuario, IdRol),
    CONSTRAINT FK_USUARIO_ROLES_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id),
    CONSTRAINT FK_USUARIO_ROLES_ROL FOREIGN KEY (IdRol) REFERENCES ROLES(Id)
);
GO

CREATE TABLE CLIENTES (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Documento VARCHAR(20) NULL UNIQUE,
    Email VARCHAR(100) NULL,
    Telefono VARCHAR(50) NULL,
    Direccion VARCHAR(200) NULL,
    Localidad VARCHAR(100) NULL,
    CondicionIVA VARCHAR(50) NULL,
    Habilitado BIT NOT NULL DEFAULT(1)
);
GO

CREATE TABLE VENTAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdUsuario INT NOT NULL,
    IdCliente INT NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
    NumeroFactura VARCHAR(50) NULL,
    MetodoPago VARCHAR(50) NULL,
    Total MONEY NOT NULL, 
    CONSTRAINT FK_VENTAS_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id),
    CONSTRAINT FK_VENTAS_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTES(Id)
);
GO

CREATE TABLE DETALLE_VENTA (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdVenta INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,
    PrecioUnitario MONEY NOT NULL, 
    CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (IdVenta) REFERENCES VENTAS(Id),
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id)
);
GO

CREATE TABLE COMPRAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdProveedor INT NOT NULL,
    IdUsuario INT NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT GETDATE(),
    Observaciones NVARCHAR(500),
    FOREIGN KEY (IdProveedor) REFERENCES PROVEEDORES(Id),
    FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(Id)
);
GO

CREATE TABLE COMPRA_LINEAS (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    IdCompra INT NOT NULL,
    IdProducto INT NOT NULL,
    Cantidad INT NOT NULL,
    PrecioUnitario DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (IdCompra) REFERENCES COMPRAS(Id),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(Id)
);
GO

