USE COMERCIO_DB;
GO

PRINT '=== Deshabilitando constraints ===';
EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL";

PRINT '=== Borrando datos ===';

-- 1) Tablas que dependen de ventas
DELETE FROM DETALLE_VENTA;
DELETE FROM VENTAS;

-- 2) Tablas que dependen de compras
DELETE FROM COMPRA_LINEAS;
DELETE FROM COMPRAS;

-- 3) Tablas auxiliares de productos
DELETE FROM PRECIOS_COMPRA;
DELETE FROM PRODUCTO_PROVEEDOR;

-- 4) Clientes
DELETE FROM CLIENTES;

-- 5) NO BORRAR usuarios ni usuario_roles
-- DELETE FROM USUARIO_ROLES;
-- DELETE FROM USUARIOS;

-- 6) Productos y proveedores
DELETE FROM PRODUCTOS;
DELETE FROM PROVEEDORES;

-- 7) Categorías y marcas
DELETE FROM CATEGORIAS;
DELETE FROM MARCAS;

PRINT '=== Rehabilitando constraints ===';
EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL";

PRINT '=== Reset de identidades ===';
DBCC CHECKIDENT ('MARCAS', RESEED, 0);
DBCC CHECKIDENT ('CATEGORIAS', RESEED, 0);
DBCC CHECKIDENT ('PROVEEDORES', RESEED, 0);
DBCC CHECKIDENT ('PRODUCTOS', RESEED, 0);
DBCC CHECKIDENT ('PRECIOS_COMPRA', RESEED, 0);

-- Usuarios y roles NO se resetean
-- DBCC CHECKIDENT ('USUARIOS', RESEED, 0);
-- DBCC CHECKIDENT ('ROLES', RESEED, 0); -- tampoco

DBCC CHECKIDENT ('CLIENTES', RESEED, 0);
DBCC CHECKIDENT ('VENTAS', RESEED, 0);
DBCC CHECKIDENT ('DETALLE_VENTA', RESEED, 0);
DBCC CHECKIDENT ('COMPRAS', RESEED, 0);
DBCC CHECKIDENT ('COMPRA_LINEAS', RESEED, 0);

PRINT '=== Base limpia (sin tocar usuarios ni roles) ===';
GO
